(function(g){var window=this;var gwa=function(a,b){return g.Jb(a,b)},Z5=function(a,b,c){a.w.set(b,c)},$5=function(a){Z5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.B)()).toString(36));
return a},a6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.bn(a.w,b,c)},hwa=function(a,b){var c=[];
g.ik(b,function(d){try{var e=g.ao.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.$n(e)&&c.push(d)},a);
return c},iwa=function(a,b){var c=hwa(a,b);
(0,g.x)(c,function(d){g.ao.prototype.remove.call(this,d)},a)},jwa=function(a){if(a.Uc){if(a.Uc.locationOverrideToken)return{locationOverrideToken:a.Uc.locationOverrideToken};
if(null!=a.Uc.latitudeE7&&null!=a.Uc.longitudeE7)return{latitudeE7:a.Uc.latitudeE7,longitudeE7:a.Uc.longitudeE7}}return null},kwa=function(a,b){g.$a(a,b)||a.push(b)},b6=function(a){var b=0,c;
for(c in a)b++;return b},lwa=function(a,b){var c=b instanceof g.tc?b:g.yc(b,/^data:image\//i.test(b));
a.src=g.uc(c)},c6=function(){},mwa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},nwa=function(a){if(a.Ed&&"function"==typeof a.Ed)return a.Ed();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Fb(a)},owa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)(0,g.x)(a,b,void 0);else{if(a.se&&"function"==typeof a.se)var c=a.se();else if(a.Ed&&"function"==typeof a.Ed)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Gb(a);d=nwa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},pwa=function(a,b,c,d){var e=new g.Qm(null,void 0);
a&&g.Rm(e,a);b&&g.Sm(e,b);c&&g.Tm(e,c);d&&(e.u=d);return e},d6=function(a,b){g.No[a]=!0;
var c=g.Lo();c&&c.publish.apply(c,arguments);g.No[a]=!1},e6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Nm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",qwa(this,a.capabilities||""),rwa(this,a.experiments||""))},qwa=function(a,b){a.capabilities.clear();
(0,g.ue)(b.split(","),g.Qa(gwa,swa)).forEach(function(c){a.capabilities.add(c)})},rwa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},f6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},g6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},twa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},uwa=function(a){return new f6(a)},vwa=function(a){return Array.isArray(a)?(0,g.Dc)(a,uwa):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return Array.isArray(a)?"["+(0,g.Dc)(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},wwa=function(a){return(0,g.Dc)(a,function(b){return{key:b.id,
name:b.name}})},k6=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},l6=function(a,b){return g.Xa(a,function(c){return g6(c,b)})},xwa=function(){var a=(0,g.os)();
a&&iwa(a,a.o.cg(!0))},m6=function(){var a=g.rs("yt-remote-connected-devices")||[];
g.rb(a);return a},ywa=function(a){if(g.ab(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Dc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},zwa=function(a){g.qs("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.rs("yt-remote-device-id");a||(a=j6(),g.qs("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.$a(a,b);g.us()&&g.ub(a,b);a=ywa(a);if(g.ab(a))try{g.Cq("remote_sid")}catch(c){}else try{g.Aq("remote_sid",a.join(","),-1)}catch(c){}},Awa=function(){return g.rs("yt-remote-session-browser-channel")},Bwa=function(){return g.rs("yt-remote-local-screens")||[]},Cwa=function(){g.qs("yt-remote-lounge-token-expiration",!0,86400)},Dwa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Dc)(Bwa(),function(d){return d.loungeToken}),c=(0,g.Dc)(a,function(d){return d.loungeToken});
(0,g.ui)(c,function(d){return!g.$a(b,d)})&&Cwa();
g.qs("yt-remote-local-screens",a,31536E3)},Ewa=function(a,b){g.qs("yt-remote-session-browser-channel",a);
g.qs("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.$a(c,d)||c.push(d);zwa(c);p6()},q6=function(a){a||(g.ts("yt-remote-session-screen-id"),g.ts("yt-remote-session-video-id"));
p6();a=m6();g.db(a,o6());zwa(a)},Fwa=function(){if(!r6){var a=g.lo();
a&&(r6=new g.Vn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},Gwa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Hwa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?Iwa(a.shift(),function(){s6(a)}):t6()},Jwa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Iwa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=Hwa();
a&&a(!1,"No cast extension found")},Lwa=function(){if(Kwa){var a=2,b=Hwa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Iwa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},Mwa=function(){Lwa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.z.call(this);
this.C=null!=c?(0,g.w)(a,c):a;this.Ad=b;this.B=(0,g.w)(this.fF,this);this.o=!1;this.u=0;this.w=this.Ha=null;this.A=[]},v6=function(a,b,c){g.z.call(this);
this.w=null!=c?(0,g.w)(a,c):a;this.Ad=b;this.u=(0,g.w)(this.gF,this);this.o=[]},w6=function(a){a.Ha=g.Uf(a.u,a.Ad);
a.w.apply(null,a.o)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return mwa(a)},y6=function(){},z6=function(){},Nwa=function(){},Pwa=function(a){return(a=Owa(a))?new ActiveXObject(a):new XMLHttpRequest},Owa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.A1(this);this.u=new g.Tf;this.u.setInterval(250)},Rwa=function(a,b,c){a.Mj=1;
a.Vg=$5(b.clone());a.fj=c;a.C=!0;Qwa(a,null)},B6=function(a,b,c,d,e){a.Mj=1;
a.Vg=$5(b.clone());a.fj=null;a.C=c;e&&(a.UB=!1);Qwa(a,d)},Qwa=function(a,b){a.Hk=(0,g.B)();
C6(a);a.Th=a.Vg.clone();a6(a.Th,"t",a.F);a.Wm=0;a.Mc=a.o.ur(a.o.Mm()?b:null);0<a.hs&&(a.Np=new v6((0,g.w)(a.OC,a,a.Mc),a.hs));a.A.la(a.Mc,"readystatechange",a.ON);var c=a.Di?g.Pb(a.Di):{};a.fj?(a.xq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Mc.send(a.Th,a.xq,a.fj,c)):(a.xq="GET",a.UB&&!g.je&&(c.Connection="close"),a.Mc.send(a.Th,a.xq,null,c));a.o.ff(1)},Uwa=function(a,b,c){for(var d=!0;!a.li&&a.Wm<c.length;){var e=Swa(a,c);
if(e==D6){4==b&&(a.mh=4,E6(15),d=!1);break}else if(e==Twa){a.mh=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.mh=1,E6(17),d=!1);a.hf=a.hf&&d;d||(G6(a),H6(a))},Swa=function(a,b){var c=a.Wm,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return Twa;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Wm=d+c;return e},Wwa=function(a,b){a.Hk=(0,g.B)();
C6(a);var c=b?window.location.hostname:"";a.Th=a.Vg.clone();Z5(a.Th,"DOMAIN",c);Z5(a.Th,"t",a.F);try{a.mf=new ActiveXObject("htmlfile")}catch(n){G6(a);a.mh=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in Vwa)k=I6[l]=Vwa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Wc(g.Yb("b/12014412"),d+"</body></html>");a.mf.open();a.mf.write(g.Rc(c));a.mf.close();a.mf.parentWindow.m=(0,g.w)(a.jN,a);a.mf.parentWindow.d=(0,g.w)(a.cB,a,!0);a.mf.parentWindow.rpcClose=(0,g.w)(a.cB,a,!1);c=a.mf.createElement("DIV");a.mf.parentWindow.document.body.appendChild(c);d=g.xc(a.Th.toString());d=g.dd(g.uc(d));d=g.Wc(g.Yb("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Xc(c,d);a.o.ff(1)},C6=function(a){a.fv=(0,g.B)()+a.B;
Xwa(a,a.B)},Xwa=function(a,b){if(null!=a.Uk)throw Error("WatchDog timer not null");
a.Uk=J6((0,g.w)(a.rN,a),b)},K6=function(a){a.Uk&&(g.v.clearTimeout(a.Uk),a.Uk=null)},H6=function(a){a.o.Mx()||a.li||a.o.mo(a)},G6=function(a){K6(a);
g.He(a.Np);a.Np=null;a.u.stop();g.$qa(a.A);if(a.Mc){var b=a.Mc;a.Mc=null;b.abort();b.dispose()}a.mf&&(a.mf=null)},F6=function(a,b){try{a.o.UA(a,b),a.o.ff(4)}catch(c){}},Zwa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Ywa(a,b,function(k){k?c(!0):g.v.setTimeout(function(){Zwa(a,b,c,d,f)},f)})}},Ywa=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
lwa(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},$wa=function(a){this.o=a;
this.u=new y6},axa=function(a){var b=M6(a.o,a.jl,"/mail/images/cleardot.gif");
$5(b);Zwa(b.toString(),5E3,(0,g.w)(a.cE,a),3,2E3);a.ff(1)},O6=function(a){var b=a.o.I;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Td=new A6(a,void 0,void 0,void 0),a.Td.Di=a.ds,b=a.o,b=M6(b,b.Mm()?a.Kl:null,a.gs),E6(5),!g.he||g.Ld(10))a6(b,"TYPE","xmlhttp"),B6(a.Td,b,!1,a.Kl,!1);else{a6(b,"TYPE","html");var c=a.Td;a=!!a.Kl;c.Mj=3;c.Vg=$5(b.clone());Wwa(c,a)}},P6=function(a){g.gf.call(this);
this.headers=new g.Nm;this.T=a||null;this.w=!1;this.R=this.o=null;this.ga=this.I="";this.C=0;this.A="";this.B=this.Z=this.G=this.U=!1;this.F=0;this.P=null;this.da="";this.M=this.aa=!1},bxa=function(a){return g.he&&g.Kd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},cxa=function(a){return"content-type"==a.toLowerCase()},exa=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;dxa(a);Q6(a)},dxa=function(a){a.U||(a.U=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},gxa=function(a){if(a.w&&"undefined"!=typeof g.F1)if(a.R[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.Uf(a.QA,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.nd(1,String(a.I));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!fxa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";dxa(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){hxa(a);
var c=a.o,d=a.R[0]?g.Ia:null;a.o=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},hxa=function(a){a.o&&a.M&&(a.o.ontimeout=null);
a.P&&(g.v.clearTimeout(a.P),a.P=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.ga+" "+a.I+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.I=null!=b?b:null;this.C=c||!1},ixa=function(a,b){this.o=a;
this.map=b;this.context=null},jxa=function(a){g.Je.call(this,"statevent",a)},kxa=function(a,b){g.Je.call(this,"timingevent",a);
this.size=b},lxa=function(a){g.Je.call(this,"serverreachability",a)},oxa=function(a){mxa(a);
if(3==a.o){var b=a.qm++,c=a.Vn.clone();Z5(c,"SID",a.w);Z5(c,"RID",b);Z5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.Mj=2;b.Vg=$5(c.clone());lwa(new Image,b.Vg.toString());b.Hk=(0,g.B)();C6(b)}nxa(a)},pxa=function(a){a.AE(1,0);
a.Vn=M6(a,null,a.Zr);W6(a)},mxa=function(a){a.Yg&&(a.Yg.abort(),a.Yg=null);
a.fc&&(a.fc.cancel(),a.fc=null);a.dg&&(g.v.clearTimeout(a.dg),a.dg=null);X6(a);a.Ld&&(a.Ld.cancel(),a.Ld=null);a.eh&&(g.v.clearTimeout(a.eh),a.eh=null)},qxa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new ixa(a.FJ++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.Ld||a.eh||(a.eh=J6((0,g.w)(a.bB,a),0),a.Ej=0)},sxa=function(a,b){if(1==a.o){if(!b){a.qm=Math.floor(1E5*Math.random());
var c=a.qm++,d=new A6(a,"",c,void 0);d.Di=null;var e=Y6(a),f=a.Vn.clone();Z5(f,"RID",c);Z5(f,"CVER","1");V6(a,f);Rwa(d,f,e);a.Ld=d;a.o=2}}else 3==a.o&&(b?rxa(a,b):0==a.u.length||a.Ld||rxa(a))},rxa=function(a,b){if(b)if(6<a.mi){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.qm-1;var d=Y6(a)}else c=b.G,d=b.fj;else c=a.qm++,d=Y6(a);var e=a.Vn.clone();Z5(e,"SID",a.w);Z5(e,"RID",c);Z5(e,"AID",a.ak);V6(a,e);c=new A6(a,a.w,c,a.Ej+1);c.Di=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ld=c;Rwa(c,e,d)},V6=function(a,b){if(a.wd){var c=a.wd.ix();
c&&g.zb(c,function(d,e){Z5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.mi&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.mi?e:f-d;try{g.zb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},txa=function(a){a.fc||a.dg||(a.F=1,a.dg=J6((0,g.w)(a.aB,a),0),a.vj=0)},Z6=function(a){if(a.fc||a.dg||3<=a.vj)return!1;
a.F++;a.dg=J6((0,g.w)(a.aB,a),uxa(a,a.vj));a.vj++;return!0},N6=function(a,b,c){a.uq=c;
a.yf=b.ug;a.C||pxa(a)},X6=function(a){null!=a.ti&&(g.v.clearTimeout(a.ti),a.ti=null)},uxa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.wd&&(c=null);var d=(0,g.w)(a.yO,a);c||(c=new g.Qm("//www.google.com/images/cleardot.gif"),$5(c));Ywa(c.toString(),1E4,d)}else E6(2);vxa(a,b)},vxa=function(a,b){a.o=0;
a.wd&&a.wd.yw(b);nxa(a);mxa(a)},nxa=function(a){a.o=0;
a.yf=-1;if(a.wd)if(0==a.A.length&&0==a.u.length)a.wd.jr();else{g.gb(a.A);var b=g.gb(a.u);a.A.length=0;a.u.length=0;a.wd.jr(b)}},M6=function(a,b,c){var d=g.Ym(c);
if(""!=d.o)b&&g.Sm(d,b+"."+d.o),g.Tm(d,d.A);else{var e=window.location;d=pwa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Al&&g.zb(a.Al,function(f,k){Z5(d,k,f)});
Z5(d,"VER",a.mi);V6(a,d);return d},J6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new jxa(a7,a))},wxa=function(){},xxa=function(){this.o=[];
this.u=[]},yxa=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.z.call(this);
this.o=new g.H(this.cN,0,this);g.A(this,this.o);this.Ad=5E3;this.u=0;if(g.Ma(a))b&&(a=(0,g.w)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.w)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.P=a;
this.C=b;this.w=new g.Un;this.u=new b7(this.bO,this);this.o=null;this.ub=!1;this.B=null;this.I="";this.G=this.A=0;this.F=[];this.M=c||!1},zxa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.uq,sessionId:a.o.w,arrayId:a.o.ak}},Axa=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&sxa(a.o),oxa(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},Bxa=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.nd(4,a))||"";b&&(this.port=":"+b);this.domain=g.od(a)||"";a=g.Jc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.qc(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.yd(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.A,d,!0),onError:g.Qa(a.w,e),le:g.Qa(a.B,e)};c&&(a.sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.tq(b,a)},Fxa=function(){var a=Cxa;
Dxa();h7.push(a);Exa(h7)},i7=function(a,b){Dxa();
var c=h7,d=Gxa(a,String(b));g.ab(c)?Hxa(d):(Exa(c),(0,g.x)(c,function(e){e(d)}))},Dxa=function(){h7||(h7=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",h7,void 0))},Hxa=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},Exa=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.x)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Gxa=function(a,b){var c=((0,g.B)()-Ixa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.N.call(this);
this.F=a;this.o=[]},Jxa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},Kxa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.ue)(a.o,function(f){return!!k6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Jxa(a,b[d])||c;return c},Lxa=function(a,b){var c=a.o.length;
a.o=(0,g.ue)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.N.call(this);
this.C=a;this.A=b;this.B=c;this.w=d;this.u=0;this.o=null;this.Ha=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+i6(this.o))},Mxa=function(a){if(a.o.length){var b=(0,g.Dc)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.w)(a.qF,a),(0,g.w)(a.pF,a))}},o7=function(a){var b=vwa(Bwa());
b=(0,g.ue)(b,function(c){return!c.uuid});
return Kxa(a,b)},q7=function(a,b){Dwa((0,g.Dc)(a.o,twa));
b&&Cwa()},s7=function(a,b){g.N.call(this);
this.C=b;var c=g.rs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.Kk(this.o))},Nxa=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.w)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.w)(function(){c(!1)},a))},t7=function(a,b){a:if(b6(b)!=b6(a.o))var c=!1;
else{c=g.Gb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Kk(a.o)),a.o=b,a.S("screenChange"));Oxa(a)},u7=function(a){isNaN(a.w)||g.Ko(a.w);
a.w=g.Io((0,g.w)(a.uu,a),0<a.A&&a.A<(0,g.B)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},Pxa=function(a){var b={};
(0,g.x)(a.C(),function(c){c.token?b[c.token]=c.id:this.Vb("Requesting availability of screen w/o lounge token.")});
return b},Oxa=function(a){a=g.Gb(g.Ab(a.o,function(b){return b}));
g.rb(a);a.length?g.qs("yt-remote-online-screen-ids",a.join(","),60):g.ts("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};Qxa(this)},Sxa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.fe();if(k=(c?l6(k,c):null)||l6(k,b)){k.uuid=b;var l=w7(a,k);Nxa(a.u,l,function(m){e(m?l:null)})}else c?Rxa(a,c,(0,g.w)(function(m){var n=w7(this,new f6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Nxa(this.u,n,function(q){e(q?n:null)})},a),f):e(null)},Txa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},Rxa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.tq(f7(a.C,"/pairing/get_lounge_token_batch"),e)},Uxa=function(a){a.o=a.w.fe();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.o))},Qxa=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.w)(a.yF,a));Uxa(a);a.A=vwa(g.rs("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+i6(a.A));a.u=new s7(a.C,(0,g.w)(a.fe,a,!0));a.u.subscribe("screenChange",(0,g.w)(function(){this.S("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.qs("yt-remote-automatic-screen-cache",(0,g.Dc)(a.A,twa)));x7(a);a.B[b.uuid]=b.id;g.qs("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.rs("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.N.call(this);
this.R=c;this.I=a;this.u=b;this.w=null},z7=function(a,b){i7(a.R,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.w)(this.hP,this);this.B=(0,g.w)(this.zN,this);this.A=g.Io((0,g.w)(function(){Vxa(this,null)},this),12E4)},Wxa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.w)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Kk(b))},Vxa=function(a,b){g.Ko(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.w)(a.Fp,a),d=(0,g.w)(a.ke,a);a.Ex(b,c,d,5)}}else a.ke(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.P="";this.T=c;this.B=null;this.F=g.Ia;this.C=NaN;this.M=(0,g.w)(this.kP,this);this.o=g.Ia},Xxa=function(a){a.o=a.I.UC(a.P,a.u.label,a.u.friendlyName,(0,g.w)(function(b){this.o=g.Ia;
this.Fp(b)},a),(0,g.w)(function(b){this.o=g.Ia;
this.ke(b)},a))},Yxa=function(a){var b={};
b.pairingCode=a.P;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Fwa()&&(b.env_useStageMdx=1);return g.wd(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.Io((0,g.w)(this.bk,this,null),150)},D7=function(a,b,c,d){g.N.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.w)(this.oM,this)},Zxa=function(a,b){return b?g.Xa(a.w,function(c){return g6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},Cxa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.He(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.u):a.S("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.w)(a.ZA,a,b)),b.w?a.S("yt-remote-cast2-session-change",b.w):c&&a.o.bk(null)):a.S("yt-remote-cast2-session-change",null))},$xa=function(a){var b=a.u.TC(),c=a.o&&a.o.u;
a=(0,g.Dc)(b,function(d){c&&g6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Zxa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},fya=function(a,b,c,d,e,f,k){aya()?bya(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?cya(a,c):(window.__onGCastApiAvailable=function(l,m){l?cya(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),g.ts("yt-remote-cast-available"),g.ts("yt-remote-cast-receiver"),dya(),c(!1))},d?g.Uo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Mwa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(Lwa(),s6(eya.map(Jwa))))):H7("Cannot initialize because not running Chrome")},dya=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);gya(!1);g.Qo(M7);M7.length=0},N7=function(){return!!g.rs("yt-remote-cast-installed")},hya=function(){var a=g.rs("yt-remote-cast-receiver");
return a?a.friendlyName:null},iya=function(){H7("clearCurrentReceiver");
g.ts("yt-remote-cast-receiver")},jya=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.Po("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},aya=function(){var a=0<=g.Jc.search(/ (CrMo|Chrome|CriOS)\//);
return g.qt||a},kya=function(a,b){L7().init(a,b)},bya=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.qs("yt-remote-cast-available",f);d6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.qs("yt-remote-cast-receiver",f);d6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.qs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+h6(f));
f||g.ts("yt-remote-cast-receiver");d6("yt-remote-cast2-session-change",f)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},cya=function(a,b){K7(!0);
I7(!1);kya(a,function(c){c?(gya(!0),g.Ro("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),g.ts("yt-remote-cast-available"),g.ts("yt-remote-cast-receiver"),dya());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.qs("yt-remote-cast-installed",a)},O7=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},gya=function(a){H7("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.zf=!1;this.I=this.G=this.u=this.B=0;this.A=NaN;this.w=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.zf=!1;a.hasNext=!1;a.F=0;a.C=(0,g.B)();a.B=0;a.u=0;a.G=0;a.I=0;a.A=NaN;a.w=!1},T7=function(a){return a.eb()?((0,g.B)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.B)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.B)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Qb(a.o);b.hasPrevious=a.zf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.B;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},Z7=function(a,b){g.N.call(this);
this.o=0;this.A=a;this.C=[];this.B=new xxa;this.w=this.u=null;this.I=(0,g.w)(this.nK,this);this.F=(0,g.w)(this.rm,this);this.G=(0,g.w)(this.mK,this);this.P=(0,g.w)(this.xK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.jv,this),lya(this))):c=3;0!=c&&(b?this.jv(c):g.Io((0,g.w)(function(){this.jv(c)},this),0));
var d=jya();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.P)},$7=function(a){return new R7(a.A.getPlayerContextData())},lya=function(a){(0,g.x)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Qa(this.lM,b),this))},a)},mya=function(a){(0,g.x)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){mya(a);
a.A.setPlayerContextData(X7(b));lya(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.I),a.w.removeMediaListener(a.F),a.rm(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.I),a.w.addMediaListener(a.F),a.w.media.length&&a.rm(a.w.media[0]))},nya=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.w)(function(d){this.Vb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Vb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.N.call(this);
this.B=NaN;this.M=!1;this.G=this.F=this.I=this.P=NaN;this.R=[];this.A=this.C=this.w=this.Wa=this.o=null;this.U=a;this.R.push(g.ep(window,"beforeunload",(0,g.w)(this.iF,this)));this.u=[];this.Wa=new R7;this.T=b.id;this.o=oya(this,c);this.o.subscribe("handlerOpened",this.rK,this);this.o.subscribe("handlerClosed",this.oK,this);this.o.subscribe("handlerError",this.pK,this);this.o.subscribe("handlerMessage",this.qK,this);Bxa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Wa.videoId;
g.us()&&g.qs("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},oya=function(a,b){return new c7(f7(a.U,"/bc"),b)},h8=function(a,b){a.S("proxyStateChange",b)},pya=function(a){a.B=g.Io((0,g.w)(function(){g8("Connecting timeout");
this.Bj(1)},a),2E4)},i8=function(a){g.Ko(a.B);
a.B=NaN},j8=function(a){g.Ko(a.P);
a.P=NaN},qya=function(a){k8(a);
a.I=g.Io((0,g.w)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.Ko(a.I);
a.I=NaN},sya=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.Cx()&&a.Wa.reset(),h8(a,1),l8(a,"getNowPlaying"),rya(a)):a.Bj(1)},tya=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Wa.videoId&&(g.Mb(b.params)?a.Wa.o=null:a.Wa.o=b.params,a.S("remotePlayerChange"))},uya=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Wa.listId=b.params.listId||a.Wa.listId;W7(a.Wa,c,d);a.S("remoteQueueChange")},wya=function(a,b){b.params=b.params||{};
uya(a,b);vya(a,b);a.S("autoplayDismissed")},vya=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Wa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Wa.playerState&&(c=-1E3);a.Wa.playerState=c;c=Number(b.params.loadedTime);a.Wa.I=isNaN(c)?0:c;c=Number(b.params.duration);a.Wa.G=isNaN(c)?0:c;c=a.Wa;var d=Number(b.params.liveIngestionTime);c.A=d;c.w=isNaN(d)?!1:!0;c=a.Wa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Wa.playerState?qya(a):k8(a);a.S("remotePlayerChange")},xya=function(a,b){if(-1E3!=
a.Wa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Wa.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Wa,isNaN(c)?0:c);a.S("remotePlayerChange")}},yya=function(a,b){var c="true"==b.params.muted;
a.Wa.volume=parseInt(b.params.volume,10);a.Wa.muted=c;a.S("remotePlayerChange")},zya=function(a,b){a.C=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},Aya=function(a,b){var c="true"==b.params.hasNext;
a.Wa.zf="true"==b.params.hasPrevious;a.Wa.hasNext=c;a.S("previousNextChange")},rya=function(a){g.Ko(a.G);
a.G=g.Io((0,g.w)(a.Bj,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Kk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.zd=a;this.u=[];this.u.push(this.zd.$_s("screenChange",(0,g.w)(this.fP,this)));this.u.push(this.zd.$_s("onlineScreenChange",(0,g.w)(this.PL,this)))},Fya=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.K("MDX_CONFIG")||b;xwa();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),Fwa()&&(n8.o="/api/loungedev"));o8||(o8=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",o8,void 0));Bya();var c=p8();if(!c){var d=new v7(n8);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);fya(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){d6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Kk(b)),s8.push(g.Po("yt-remote-cast2-availability-change",function(){d6("yt-remote-receiver-availability-change")})),s8.push(g.Po("yt-remote-cast2-receiver-selected",function(){t8(null);
d6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.Po("yt-remote-cast2-receiver-resumed",function(){d6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.Po("yt-remote-cast2-session-change",Cya)),s8.push(g.Po("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),iya())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.yo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Kk(a)),Dya(a),c.start(),q8()||Eya())},Hya=function(){var a=Gya();
N7()&&g.rs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Gya=function(){var a=p8().zd.$_gos();
var b=w8();b&&x8()&&(k6(a,b)||a.push(b));return wwa(a)},y8=function(){var a=Iya();
!a&&N7()&&hya()&&(a={key:"cast-selector-receiver",name:hya()});return a},Iya=function(){var a=Gya(),b=w8();
b||(b=u8());return g.Xa(a,function(c){return b&&g6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().fe();return l6(b,a)},Cya=function(a){r8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.Ha("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},Jya=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},Kya=function(){return g.Ha("yt.mdx.remote.connectData_")},t8=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.Ha("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||Jya("");g.Fa("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.x)(o8,function(c){c(a)}),o8.length=0);
b&&!a?d6("yt-remote-connection-change",!1):!b&&a&&d6("yt-remote-connection-change",!0)},u8=function(){var a=g.us();
if(!a)return null;var b=p8();if(!b)return null;b=b.fe();return l6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{Jya(a.id);var c=new f8(n8,a,v8());c.connect(b,Kya());c.subscribe("beforeDisconnect",function(d){d6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},Eya=function(){var a=u8();
a?(r8("Resume connection to: "+h6(a)),A8(a,0)):(q6(),iya(),r8("Skipping connecting because no session screen found."))},Bya=function(){var a=v8();
if(g.Mb(a)){a=o6();var b=g.rs("yt-remote-session-name")||"",c=g.rs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},Dya=function(a){a?(g.qs("yt-remote-session-app",a.app),g.qs("yt-remote-session-name",a.name)):(g.ts("yt-remote-session-app"),g.ts("yt-remote-session-name"));
g.Fa("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a){g.Q.call(this,{D:"div",
H:"ytp-remote",K:[{D:"div",H:"ytp-remote-display-status",K:[{D:"div",H:"ytp-remote-display-status-icon",K:[g.EM()]},{D:"div",H:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.u=new g.iN(this,250);g.A(this,this.u);this.w=a;this.L(a,"presentingplayerstatechange",this.A);Lya(this,g.UK(a))},Lya=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.lM("Error on $RECEIVER_NAME",c):b.eb()||g.U(b,4)?g.lM("Playing on $RECEIVER_NAME",c):g.lM("Connected to $RECEIVER_NAME",c);a.ma("statustext",c);a.u.show()}else a.u.hide()},H8=function(a,b,c){g.z.call(this);
var d=this;this.module=a;this.J=b;this.Qa=c;this.events=new g.ur(this);this.I=this.events.L(this.J,"onVolumeChange",this.zA);this.A=!1;this.suggestion=null;this.B=new g.wC(64);this.o=new g.H(this.fC,500,this);this.u=new g.H(this.gC,1E3,this);this.F=new u6(this.HO,0,this);this.w={};this.G=new g.H(this.GC,1E3,this);this.C=new v6(this.seekTo,1E3,this);this.P=g.Ia;g.A(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.mL);this.events.L(b,"captionschanged",this.lK);this.events.L(b,"captionssettingschanged",
this.hC);this.events.L(b,"videoplayerreset",this.Gp);this.events.L(b,"mdxautoplaycancel",function(){d.Qa.Pw()});
a=this.Qa;a.fa();a.subscribe("proxyStateChange",this.TA,this);a.subscribe("remotePlayerChange",this.xm,this);a.subscribe("remoteQueueChange",this.Gp,this);a.subscribe("previousNextChange",this.PA,this);a.subscribe("nowAutoplaying",this.LA,this);a.subscribe("autoplayDismissed",this.kA,this);g.A(this,this.o);g.A(this,this.u);g.A(this,this.F);g.A(this,this.G);g.A(this,this.C);this.hC();this.Gp();this.xm()},Mya=function(a){a.Pb(0);
a.o.stop();I8(a,new g.wC(64))},K8=function(a,b){if(J8(a)&&!a.A){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Sb(c,b));a.Qa.RC(a.J.getVideoData(1).videoId,c);a.w=$7(a.Qa).o}},L8=function(a,b){var c=a.J.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.Qa.playVideo(c.videoId,b,d,e,c.playerParams,c.Bf,jwa(c));I8(a,new g.wC(1))},Nya=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{dy:1});
c&&c.length?(a.J.setOption("captions","track",b),a.A=!1):(a.J.loadModule("captions"),a.A=!0)}else a.J.setOption("captions","track",{})},J8=function(a){return $7(a.Qa).videoId===a.J.getVideoData(1).videoId},I8=function(a,b){a.u.stop();
var c=a.B;if(!g.CC(c,b)){var d=g.U(b,2);d!==g.U(a.B,2)&&g.PS(a.J.app,d);a.B=b;Oya(a.module,c,b)}},M8=function(){g.Q.call(this,{D:"div",
H:"ytp-mdx-manual-pairing-popup-dialog",O:{role:"dialog"},K:[{D:"div",H:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",H:"ytp-mdx-manual-pairing-popup-title",W:"Connecting to your TV on web using a code will be going away soon"},{D:"div",H:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],W:"Learn more"},{D:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],W:"OK"}]}]}]});this.u=new g.iN(this,250);this.learnMoreButton=
this.o["ytp-mdx-manual-pairing-popup-learn-more"];this.okButton=this.o["ytp-mdx-manual-pairing-popup-ok"];g.A(this,this.u);this.L(this.learnMoreButton,"click",this.w);this.L(this.okButton,"click",this.A)},N8=function(){g.Q.call(this,{D:"div",
H:"ytp-mdx-popup-dialog",O:{role:"dialog"},K:[{D:"div",H:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",H:"ytp-mdx-popup-title",W:"You're signed out"},{D:"div",H:"ytp-mdx-popup-description",W:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",H:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],
W:"Confirm"}]}]}]});this.u=new g.iN(this,250);this.cancelButton=this.o["ytp-mdx-privacy-popup-cancel"];this.confirmButton=this.o["ytp-mdx-privacy-popup-confirm"];g.A(this,this.u);this.L(this.cancelButton,"click",this.w);this.L(this.confirmButton,"click",this.A)},O8=function(a,b){g.ON.call(this,"Play on",0,a,b);
this.J=a;this.Sh={};this.L(a,"onMdxReceiversChange",this.C);this.L(a,"presentingplayerstatechange",this.C);this.C()},P8=function(a){g.AL.call(this,a);
this.af={key:j6(),name:"This computer"};this.Zd=null;this.subscriptions=[];this.gu=this.Qa=null;this.Sh=[this.af];this.ah=this.af;this.Ac=new g.wC(64);this.uy=0;this.Sc=-1;this.ck=null;this.ym=this.No=!1;this.ej=this.Dk=null;if(!g.Qy(this.player.N())){a=this.player;var b=g.UB(a);b&&(b=b.jm())&&(b=new O8(a,b),g.A(this,b));b=new G8(a);g.A(this,b);g.nL(a,b.element,4);this.Dk=new N8;g.A(this,this.Dk);g.nL(a,this.Dk.element,4);g.O(this.player.N().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.ck=new M8,g.A(this,this.ck),g.nL(a,this.ck.element,4));this.ym=!!u8();this.No=!!g.rs("yt-remote-manual-pairing-warning-shown")}},Q8=function(a){a.ej&&(a.player.removeEventListener("presentingplayerstatechange",a.ej),a.ej=null)},Oya=function(a,b,c){a.Ac=c;
a.player.S("presentingplayerstatechange",new g.YG(c,b))},Pya=function(a,b,c){var d=!1;
1===b?d=!a.ym:2===b&&(d=!a.No);d&&g.$G(c,8)&&(a.player.pauseVideo(),Q8(a))},R8=function(a,b){if(b.key!==a.ah.key)if(b.key===a.af.key)z8();
else{if(a.ck&&!a.No&&b!==a.af&&"cast-selector-receiver"!==b.key&&g.Zy(a.player.N()))Qya(a);else{var c;(c=!g.O(a.player.N().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.ym||!a.Dk);(c?0:g.Zy(a.player.N())||g.cz(a.player.N()))&&Rya(a)}a.ah=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.O(a.player.N().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ba(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Bf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=jwa(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+g.Kk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=
c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?d6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().fe(),(c=l6(c,b.key))&&A8(c,1))}},Rya=function(a){g.UK(a.player).eb()?a.player.pauseVideo():(a.ej=function(b){Pya(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.ej));
a.Dk&&a.Dk.Rb();x8()||(E8=!0)},Qya=function(a){g.UK(a.player).eb()?a.player.pauseVideo():(a.ej=function(b){Pya(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.ej));
a.ck&&a.ck.Rb();x8()||(E8=!0)},Vwa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},Sya={},swa={IP:"atp",vS:"ska",gS:"que",zR:"mus",uS:"sus",KQ:"dsp",oS:"seq"},r6,n6="",Kwa=Gwa("loadCastFramework")||Gwa("loadCastApplicationFramework"),eya=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(u6,g.z);g.h=u6.prototype;g.h.eF=function(a){this.A=arguments;this.o=!1;this.Ha?this.w=(0,g.B)()+this.Ad:this.Ha=g.Uf(this.B,this.Ad)};
g.h.stop=function(){this.Ha&&(g.v.clearTimeout(this.Ha),this.Ha=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.X=function(){this.stop();u6.Eb.X.call(this)};
g.h.fF=function(){this.w?(this.Ha=g.Uf(this.B,this.w-(0,g.B)()),this.w=null):(this.Ha=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.Sa(v6,g.z);g.h=v6.prototype;g.h.Lj=!1;g.h.Jl=0;g.h.Ha=null;g.h.Lx=function(a){this.o=arguments;this.Ha||this.Jl?this.Lj=!0:w6(this)};
g.h.stop=function(){this.Ha&&(g.v.clearTimeout(this.Ha),this.Ha=null,this.Lj=!1,this.o=[])};
g.h.pause=function(){this.Jl++};
g.h.resume=function(){this.Jl--;this.Jl||!this.Lj||this.Ha||(this.Lj=!1,w6(this))};
g.h.X=function(){v6.Eb.X.call(this);this.stop()};
g.h.gF=function(){this.Ha=null;this.Lj&&!this.Jl&&(this.Lj=!1,w6(this))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Owa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Sa(Nwa,z6);S8=new Nwa;g.h=A6.prototype;g.h.Di=null;g.h.hf=!1;g.h.Uk=null;g.h.fv=null;g.h.Hk=null;g.h.Mj=null;g.h.Vg=null;g.h.Th=null;g.h.fj=null;g.h.Mc=null;g.h.Wm=0;g.h.mf=null;g.h.xq=null;g.h.mh=null;g.h.Ll=-1;g.h.UB=!0;g.h.li=!1;g.h.hs=0;g.h.Np=null;var Twa={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.ON=function(a){a=a.target;var b=this.Np;b&&3==R6(a)?b.Lx():this.OC(a)};
g.h.OC=function(a){try{if(a==this.Mc)a:{var b=R6(this.Mc),c=this.Mc.C,d=this.Mc.getStatus();if(g.he&&!g.Ld(10)||g.je&&!g.Kd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.wh&&!T6(this.Mc))break a;this.li||4!=b||7==c||(8==c||0>=d?this.o.ff(3):this.o.ff(2));K6(this);var e=this.Mc.getStatus();this.Ll=e;var f=T6(this.Mc);(this.hf=200==e)?(4==b&&G6(this),this.C?(Uwa(this,b,f),g.wh&&this.hf&&3==b&&(this.A.la(this.u,"tick",this.GN),this.u.start())):F6(this,f),this.hf&&!this.li&&(4==b?this.o.mo(this):(this.hf=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.mh=3,E6(13)):(this.mh=0,E6(14)),G6(this),H6(this))}}catch(k){this.Mc&&T6(this.Mc)}finally{}};
g.h.GN=function(){var a=R6(this.Mc),b=T6(this.Mc);this.Wm<b.length&&(K6(this),Uwa(this,a,b),this.hf&&4!=a&&C6(this))};
g.h.jN=function(a){J6((0,g.w)(this.iN,this,a),0)};
g.h.iN=function(a){this.li||(K6(this),F6(this,a),C6(this))};
g.h.cB=function(a){J6((0,g.w)(this.hN,this,a),0)};
g.h.hN=function(a){this.li||(G6(this),this.hf=a,this.o.mo(this),this.o.ff(4))};
g.h.cancel=function(){this.li=!0;G6(this)};
g.h.rN=function(){this.Uk=null;var a=(0,g.B)();0<=a-this.fv?(2!=this.Mj&&this.o.ff(3),G6(this),this.mh=2,E6(18),H6(this)):Xwa(this,this.fv-a)};
g.h.getLastError=function(){return this.mh};g.h=$wa.prototype;g.h.ds=null;g.h.Td=null;g.h.Op=!1;g.h.Nx=null;g.h.Sn=null;g.h.Ns=null;g.h.gs=null;g.h.xe=null;g.h.ug=-1;g.h.Kl=null;g.h.jl=null;g.h.connect=function(a){this.gs=a;a=M6(this.o,null,this.gs);E6(3);this.Nx=(0,g.B)();var b=this.o.G;null!=b?(this.Kl=b[0],(this.jl=b[1])?(this.xe=1,axa(this)):(this.xe=2,O6(this))):(a6(a,"MODE","init"),this.Td=new A6(this,void 0,void 0,void 0),this.Td.Di=this.ds,B6(this.Td,a,!1,null,!0),this.xe=0)};
g.h.cE=function(a){if(a)this.xe=2,O6(this);else{E6(4);var b=this.o;b.yf=b.Yg.ug;$6(b,9)}a&&this.ff(2)};
g.h.ur=function(a){return this.o.ur(a)};
g.h.abort=function(){this.Td&&(this.Td.cancel(),this.Td=null);this.ug=-1};
g.h.Mx=function(){return!1};
g.h.UA=function(a,b){this.ug=a.Ll;if(0==this.xe)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.yf=this.ug;$6(c,2);return}this.Kl=c[0];this.jl=c[1]}else c=this.o,c.yf=this.ug,$6(c,2);else if(2==this.xe)if(this.Op)E6(7),this.Ns=(0,g.B)();else if("11111"==b){if(E6(6),this.Op=!0,this.Sn=(0,g.B)(),c=this.Sn-this.Nx,!g.he||g.Ld(10)||500>c)this.ug=200,this.Td.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Sn=this.Ns=(0,g.B)(),this.Op=!1};
g.h.mo=function(){this.ug=this.Td.Ll;if(this.Td.hf)0==this.xe?this.jl?(this.xe=1,axa(this)):(this.xe=2,O6(this)):2==this.xe&&((!g.he||g.Ld(10)?!this.Op:200>this.Ns-this.Sn)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.xe?E6(9):2==this.xe&&E6(10);var a=this.o;this.Td.getLastError();a.yf=this.ug;$6(a,2)}};
g.h.Mm=function(){return this.o.Mm()};
g.h.isActive=function(){return this.o.isActive()};
g.h.ff=function(a){this.o.ff(a)};g.Sa(P6,g.gf);var fxa=/^https?$/i,Tya=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.I+"; newUri="+a);b=b?b.toUpperCase():"GET";this.I=a;this.A="";this.C=0;this.ga=b;this.U=!1;this.w=!0;this.o=this.T?Pwa(this.T):Pwa(S8);this.R=this.T?this.T.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.w)(this.QA,this);try{c6(S6(this,"Opening Xhr")),this.Z=!0,this.o.open(b,String(a),!0),this.Z=!1}catch(f){c6(S6(this,"Error opening Xhr: "+f.message));exa(this,f);return}a=c||
"";var e=this.headers.clone();d&&owa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.se(),cxa);c=g.v.FormData&&a instanceof g.v.FormData;!g.$a(Tya,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.da&&(this.o.responseType=this.da);"withCredentials"in this.o&&this.o.withCredentials!==this.aa&&(this.o.withCredentials=this.aa);try{hxa(this),0<this.F&&(this.M=bxa(this.o),c6(S6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.M)),this.M?(this.o.timeout=this.F,this.o.ontimeout=(0,g.w)(this.Ox,this)):this.P=g.Uf(this.Ox,this.F,this)),c6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){c6(S6(this,"Send error: "+f.message)),exa(this,f)}};
g.h.Ox=function(){"undefined"!=typeof g.F1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.X=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.Eb.X.call(this)};
g.h.QA=function(){this.fa()||(this.Z||this.G||this.B?gxa(this):this.nM())};
g.h.nM=function(){gxa(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.Al=null;g.h.Ld=null;g.h.fc=null;g.h.Zr=null;g.h.Vn=null;g.h.kw=null;g.h.lo=null;g.h.qm=0;g.h.FJ=0;g.h.wd=null;g.h.eh=null;g.h.dg=null;g.h.ti=null;g.h.Yg=null;g.h.uq=null;g.h.ak=-1;g.h.ty=-1;g.h.yf=-1;g.h.Ej=0;g.h.vj=0;g.h.mi=8;var a7=new g.gf;g.Sa(jxa,g.Je);g.Sa(kxa,g.Je);g.Sa(lxa,g.Je);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Zr=b;this.Al=c||{};d&&void 0!==e&&(this.Al.OSID=d,this.Al.OAID=e);this.C?(J6((0,g.w)(this.Ew,this,a),100),pxa(this)):this.Ew(a)};
g.h.Ew=function(a){this.Yg=new $wa(this);this.Yg.ds=null;this.Yg.u=this.B;this.Yg.connect(a)};
g.h.Mx=function(){return 0==this.o};
g.h.bB=function(a){this.eh=null;sxa(this,a)};
g.h.aB=function(){this.dg=null;this.fc=new A6(this,this.w,"rpc",this.F);this.fc.Di=null;this.fc.hs=0;var a=this.kw.clone();Z5(a,"RID","rpc");Z5(a,"SID",this.w);Z5(a,"CI",this.uq?"0":"1");Z5(a,"AID",this.ak);V6(this,a);if(!g.he||g.Ld(10))Z5(a,"TYPE","xmlhttp"),B6(this.fc,a,!0,this.lo,!1);else{Z5(a,"TYPE","html");var b=this.fc,c=!!this.lo;b.Mj=3;b.Vg=$5(a.clone());Wwa(b,c)}};
g.h.UA=function(a,b){if(0!=this.o&&(this.fc==a||this.Ld==a))if(this.yf=a.Ll,this.Ld==a&&3==this.o)if(7<this.mi){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.dg){if(this.fc)if(this.fc.Hk+3E3<this.Ld.Hk)X6(this),this.fc.cancel(),this.fc=null;else break a;Z6(this);E6(19)}}else this.ty=c[1],0<this.ty-this.ak&&37500>c[2]&&this.uq&&0==this.vj&&!this.ti&&(this.ti=J6((0,g.w)(this.hK,this),6E3));else $6(this,11)}else b!=Sya.fQ.o&&$6(this,11);else if(this.fc==
a&&X6(this),!g.fc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.ak=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.lo=e[2],e=e[3],null!=e?this.mi=e:this.mi=6,this.o=3,this.wd&&this.wd.Aw(),this.kw=M6(this,this.Mm()?this.lo:null,this.Zr),txa(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.wd&&this.wd.zw(e),this.vj=0)}}};
g.h.hK=function(){null!=this.ti&&(this.ti=null,this.fc.cancel(),this.fc=null,Z6(this),E6(20))};
g.h.mo=function(a){if(this.fc==a){X6(this);this.fc=null;var b=2}else if(this.Ld==a)this.Ld=null,b=1;else return;this.yf=a.Ll;if(0!=this.o)if(a.hf)1==b?(b=(0,g.B)()-a.Hk,a7.dispatchEvent(new kxa(a7,a.fj?a.fj.length:0,b,this.Ej)),W6(this),this.A.length=0):txa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.yf)){if(d=1==b)this.Ld||this.eh||1==this.o||2<=this.Ej?d=!1:(this.eh=J6((0,g.w)(this.bB,this,a),uxa(this,this.Ej)),this.Ej++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.AE=function(a){if(!g.$a(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.yO=function(a){a?E6(2):(E6(1),vxa(this,8))};
g.h.ur=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.aa=!1;return a};
g.h.isActive=function(){return!!this.wd&&this.wd.isActive(this)};
g.h.ff=function(a){a7.dispatchEvent(new lxa(a7,a))};
g.h.Mm=function(){return!(!g.he||g.Ld(10))};
g.h=wxa.prototype;g.h.Aw=function(){};
g.h.zw=function(){};
g.h.yw=function(){};
g.h.jr=function(){};
g.h.ix=function(){return{}};
g.h.isActive=function(){return!0};g.h=xxa.prototype;g.h.isEmpty=function(){return g.ab(this.o)&&g.ab(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.$a(this.o,a)||g.$a(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.era)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.u,a)};
g.h.Ed=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Sa(b7,g.z);g.h=b7.prototype;g.h.cN=function(){this.Ad=Math.min(3E5,2*this.Ad);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.Ad+15E3*Math.random();this.o.Ua(a);this.u=(0,g.B)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Ad=5E3};g.Sa(c7,wxa);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.Ih=function(a){return this.w.Ei(a)};
g.h.S=function(a,b){return this.w.S.apply(this.w,arguments)};
g.h.dispose=function(){this.ub||(this.ub=!0,g.He(this.w),Axa(this),g.He(this.u),this.u=null)};
g.h.fa=function(){return this.ub};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.I="";this.u.stop();this.B=a||null;this.A=b||0;a=this.P+"/test";b=this.P+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.wd=null);d.wd=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.ak):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.Sb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&qxa(this.o,c)};
g.h.Aw=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)qxa(this.o,a[b])}this.S("handlerOpened")};
g.h.yw=function(a){var b=2==a&&401==this.o.yf;4==a||b||this.u.start();this.S("handlerError",a)};
g.h.jr=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.ix=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.Sb(a,this.B);return a};
g.h.zw=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),oxa(this.o)):this.S("handlerMessage",new yxa(a[0],a[1]))};
g.h.bO=function(){this.u.isActive();var a=this.o,b=0;a.fc&&b++;a.Ld&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var Ixa=(0,g.B)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Sa(m7,g.N);m7.prototype.fe=function(){return this.o};
m7.prototype.contains=function(a){return!!k6(this.o,a)};
m7.prototype.get=function(a){return a?l6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.N);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ha)&&this.SC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ha)||(g.Ko(this.Ha),this.Ha=NaN)};
g.h.X=function(){this.stop();g.N.prototype.X.call(this)};
g.h.SC=function(){this.Ha=NaN;this.o=g.tq(f7(this.C,"/pairing/get_screen"),{method:"POST",sb:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.w)(this.dP,this),onError:(0,g.w)(this.cP,this),le:(0,g.w)(this.eP,this)})};
g.h.dP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.w;this.S("pairingComplete",new f6(c))};
g.h.cP=function(a){this.o=null;a.status&&404==a.status?this.u>=Uya.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=Uya[this.u],this.Ha=g.Io((0,g.w)(this.SC,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.h.eP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var Uya=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.S("screenChange");!g.rs("yt-remote-lounge-token-expiration")&&Mxa(this);g.Ko(this.u);this.u=g.Io((0,g.w)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);Jxa(this,a);q7(this,!1);this.S("screenChange");b(a);a.token||Mxa(this)};
g.h.remove=function(a,b){var c=o7(this);Lxa(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.h.rq=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.h.X=function(){g.Ko(this.u);p7.Eb.X.call(this)};
g.h.qF=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.pF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.N);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.rs("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.B)()-144E5<a?0:a)?u7(this):(this.A=(0,g.B)()+3E5,g.qs("yt-remote-fast-check-period",this.A),this.uu())};
g.h.isEmpty=function(){return g.Mb(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Ab(this.o,function(c,d){return c&&!!l6(a,d)},this);
t7(this,b)};
g.h.X=function(){g.Ko(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.X.call(this)};
g.h.uu=function(){g.Ko(this.w);this.w=NaN;this.u&&this.u.abort();var a=Pxa(this);if(b6(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Gb(a).join(",")},(0,g.w)(this.LM,this,a),(0,g.w)(this.KM,this))}else t7(this,{}),u7(this)};
g.h.LM=function(a,b){this.u=null;var c=g.Gb(Pxa(this));if(g.sb(c,g.Gb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Vb("Changing Screen set during request."),this.uu()};
g.h.KM=function(a){this.Vb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Vb=function(a){i7("OnlineScreenService",a)};g.Sa(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.S("screenChange"),this.u.isEmpty()||this.S("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.rq=function(a,b,c,d){this.w.contains(a)?this.w.rq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.fe=function(a){return a?this.o:g.fb(this.o,(0,g.ue)(this.A,function(b){return!this.contains(b)},this))};
g.h.TC=function(){return(0,g.ue)(this.fe(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.UC=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.w)(function(k){g.He(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.He(f);e(k)});
f.start();return(0,g.w)(f.stop,f)};
g.h.gP=function(a,b,c,d){g.tq(f7(this.C,"/pairing/get_screen"),{method:"POST",sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.w)(function(e,f){var k=new f6(f.screen||{});if(!k.name||Txa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Txa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.w)(function(e){d(Error("pairing request failed: "+e.status))},this),
le:(0,g.w)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.He(this.w);g.He(this.u);v7.Eb.X.call(this)};
g.h.yF=function(){Uxa(this);this.S("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Sa(y7,g.N);g.h=y7.prototype;g.h.Fp=function(a){this.w=a;this.S("sessionScreen",this.w)};
g.h.ke=function(a){this.fa()||(a&&z7(this,""+a),this.w=null,this.S("sessionScreen",null))};
g.h.info=function(a){i7(this.R,a)};
g.h.WC=function(){return null};
g.h.Du=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.w)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.w)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Du("");y7.Eb.X.call(this)};g.Sa(A7,y7);g.h=A7.prototype;g.h.Cu=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Wxa(this)};
g.h.bk=function(a){this.info("launchWithParams no-op for Cast: "+g.Kk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.w)(function(){this.ke()},this),(0,g.w)(function(){this.ke(Error("Failed to stop receiver app."))},this)):this.ke(Error("Stopping cast device witout session."))};
g.h.Du=g.Ia;g.h.X=function(){this.info("disposeInternal");g.Ko(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Eb.X.call(this)};
g.h.zN=function(a,b){if(!this.fa())if(b){var c=x6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kk(c));switch(d){case "mdxSessionStatus":Vxa(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.Ex=function(a,b,c,d){Sxa(this.I,this.u.label,a,this.u.friendlyName,(0,g.w)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Io((0,g.w)(this.Ex,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.WC=function(){return this.o};
g.h.hP=function(a){this.fa()||a||(z7(this,"Cast session died."),this.ke())};g.Sa(B7,y7);g.h=B7.prototype;g.h.Cu=function(a){this.A=a;this.A.addUpdateListener(this.M)};
g.h.bk=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ia;g.Ko(this.C);this.A?this.A.stop((0,g.w)(this.ke,this,null),(0,g.w)(this.ke,this,"Failed to stop DIAL device.")):this.ke()};
g.h.X=function(){this.o();this.o=g.Ia;g.Ko(this.C);this.A&&this.A.removeUpdateListener(this.M);this.A=null;B7.Eb.X.call(this)};
g.h.kP=function(a){this.fa()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ia,this.ke())};
g.h.zs=function(a){this.P=j6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Yxa(this));a(b);Xxa(this)}else this.F=(0,g.w)(function(){g.Ko(this.C);this.F=g.Ia;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Yxa(this));a(c);Xxa(this)},this),this.C=g.Io((0,g.w)(function(){this.F()},this),100)};
g.h.SF=function(a,b,c){Sxa(this.I,this.G.receiver.label,a,this.u.friendlyName,(0,g.w)(function(d){d&&d.token?(this.Fp(d),b(new chrome.cast.DialLaunchResponse(!1))):this.zs(b,c)},this),(0,g.w)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.zs(b,c)},this))};g.Sa(C7,y7);C7.prototype.stop=function(){this.ke()};
C7.prototype.Cu=g.Ia;C7.prototype.bk=function(){g.Ko(this.o);this.o=NaN;var a=l6(this.I.fe(),this.u.label);a?this.Fp(a):this.ke(Error("No such screen"))};
C7.prototype.X=function(){g.Ko(this.o);this.o=NaN;C7.Eb.X.call(this)};g.Sa(D7,g.N);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.w)(this.sM,this);c=new chrome.cast.ApiConfig(c,(0,g.w)(this.XA,this),f,d,e);c.customDialLaunchCallback=(0,g.w)(this.EK,this);chrome.cast.initialize(c,(0,g.w)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.A),Fxa(),this.u.subscribe("onlineScreenChange",(0,g.w)(this.VC,this)),this.w=$xa(this),chrome.cast.setCustomReceivers(this.w,g.Ia,(0,g.w)(function(k){this.Vb("Failed to set initial custom receivers: "+g.Kk(k))},this)),this.S("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.w)(function(k){this.Vb("Failed to initialize API: "+g.Kk(k));
b(!1)},this))};
g.h.iO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=l6(this.u.fe(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=Zxa(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ia,(0,g.w)(function(e){this.Vb("Failed to set initial custom receivers: "+g.Kk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.Du(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.jO=function(a){this.fa()?this.Vb("Setting connection data on disposed cast v2"):this.o?this.o.bk(a):this.Vb("Setting connection data without a session")};
g.h.jP=function(){this.fa()?this.Vb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.w)(this.XA,this),(0,g.w)(this.PM,this))};
g.h.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.w)(this.VC,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=Cxa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.db(b||[],a);g.He(this.o);D7.Eb.X.call(this)};
g.h.Vb=function(a){i7("Controller",a)};
g.h.ZA=function(a,b){this.o==a&&(b||G7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.h.oM=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.S("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Vb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Vb("Stopping receiver w/o session: "+a.friendlyName)}else this.Vb("onReceiverAction_ called without receiver.")};
g.h.EK=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Vb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Vb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Vb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.w)(b.SF,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.w)(b.zs,b))};
g.h.XA=function(a){if(!this.fa()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Vb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=l6(this.u.fe(),c.label);d&&g6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.He(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.w)(this.ZA,this,this.o)),this.o.bk(null));this.o.Cu(a)}}};
g.h.iP=function(){return this.o?this.o.WC():null};
g.h.PM=function(a){this.fa()||(this.Vb("Failed to estabilish a session: "+g.Kk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.sM=function(a){E7("Receiver availability updated: "+a);if(!this.fa()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.S("yt-remote-cast2-availability-change",F7(this))}};
g.h.VC=function(){this.fa()||(this.w=$xa(this),E7("Updating custom receivers: "+g.Kk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ia,(0,g.w)(function(){this.Vb("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.jO;D7.prototype.setConnectedScreenStatus=D7.prototype.iO;D7.prototype.stopSession=D7.prototype.jP;D7.prototype.getCastSession=D7.prototype.iP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];g.h=R7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.zf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.B=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.w=!isNaN(this.A))};
g.h.eb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.w?this.G+T7(this):this.G};
g.h.clone=function(){return new R7(X7(this))};g.r(Z7,g.N);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ia,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.S("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ia,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.S("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.eb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ia,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.S("remotePlayerChange")}else a8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ia,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.S("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.w)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.w)(function(){this.Vb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.w)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.w)(function(){this.Vb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Qa(this.setVolume,a,b))};
g.h.RC=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kk(b.style),g.Sb(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Qa(this.RC,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.Kp=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Qa(this.Kp,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Qa(this.nextVideo,a,b))};
g.h.Pw=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Pw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.h.X=function(){mya(this);this.A=null;this.B.clear();Y7(this,null);g.N.prototype.X.call(this)};
g.h.jv=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.ab(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.lM=function(a,b){this.S(a,b)};
g.h.nK=function(a){if(!a)this.rm(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.rm=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),nya(this),this.S("remotePlayerChange")};
g.h.mK=function(a){a?(nya(this),this.S("remotePlayerChange")):this.rm(null)};
g.h.Ou=function(){d8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.xK=function(){var a=jya();a&&Y7(this,a)};
g.h.Vb=function(a){i7("CP",a)};g.r(f8,g.N);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Wa.listId=c);this.Wa.videoId=d;this.Wa.index=k||0;this.Wa.state=3;U7(this.Wa,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Kk(l));this.o.connect({method:"setPlaylist",
params:g.Kk(l)},a,Awa())}else g8("Connecting without params"),this.o.connect({},a,Awa());pya(this)};
g.h.dispose=function(){this.fa()||(this.S("beforeDispose"),h8(this,3));g.N.prototype.dispose.call(this)};
g.h.X=function(){i8(this);k8(this);j8(this);g.Ko(this.F);this.F=NaN;g.Ko(this.G);this.G=NaN;this.w=null;g.fp(this.R);this.R.length=0;this.o.dispose();g.N.prototype.X.call(this);this.A=this.C=this.u=this.Wa=this.o=null};
g.h.iF=function(){this.Bj(2)};
g.h.rK=function(){g8("Channel opened");this.M&&(this.M=!1,j8(this),this.P=g.Io((0,g.w)(function(){g8("Timing out waiting for a screen.");this.Bj(1)},this),15E3));
Ewa(zxa(this.o),this.T)};
g.h.oK=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.pK=function(a){q6();isNaN(this.Fl())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,g8("Channel error: "+a+" with reconnection in "+this.Fl()+" ms"),h8(this,2))};
g.h.qK=function(a){a.params?g8("Received: action="+a.action+", params="+g.Kk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.Dc)(a,function(c){return new e6(c)});
a=!!g.Xa(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
sya(this,a);break;case "loungeScreenDisconnected":g.eb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
sya(this,!1);break;case "remoteConnected":var b=new e6(x6(a.params.device));g.Xa(this.u,function(c){return b?c.id==b.id:!1})||kwa(this.u,b);
break;case "remoteDisconnected":b=new e6(x6(a.params.device));g.eb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":uya(this,a);break;case "nowPlaying":wya(this,a);break;case "onStateChange":vya(this,a);break;case "onAdStateChange":xya(this,a);break;case "onVolumeChanged":yya(this,a);break;case "onSubtitlesTrackChanged":tya(this,a);break;case "nowAutoplaying":zya(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.S("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.S("autoplayModeChange",this.A);"DISABLED"==this.A&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":Aya(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.XN=function(){if(this.w){var a=this.w;this.w=null;this.Wa.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.YE=function(){var a=3;this.fa()||(a=0,isNaN(this.Fl())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.Bj=function(a){g8("Disconnecting with "+a);i8(this);this.S("beforeDisconnect",a);1==a&&q6();Axa(this.o,a);this.dispose()};
g.h.XE=function(){var a=this.Wa;this.w&&(a=this.Wa.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.kO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Wa.videoId&&(this.w=b.videoId,g.Ko(this.F),this.F=g.Io((0,g.w)(this.XN,this),5E3));var c=[];this.Wa.listId==b.listId&&this.Wa.videoId==b.videoId&&this.Wa.index==b.index||c.push("remoteQueueChange");this.Wa.playerState==b.playerState&&this.Wa.volume==b.volume&&this.Wa.muted==b.muted&&V7(this.Wa)==V7(b)&&g.Kk(this.Wa.o)==g.Kk(b.o)||c.push("remotePlayerChange");this.Wa.reset(a);(0,g.x)(c,function(d){this.S(d)},this)};
g.h.Cx=function(){var a=this.o.C.id,b=g.Xa(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Fl=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.B)():NaN};
g.h.ME=function(){return this.A||"UNSUPPORTED"};
g.h.NE=function(){return this.C||""};
g.h.bP=function(){if(!isNaN(this.Fl())){var a=this.o.u;g.vn(a.o);a.start()}};
g.h.fO=function(a,b){l8(this,a,b);rya(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.Ih;f8.prototype.getProxyState=f8.prototype.YE;f8.prototype.disconnect=f8.prototype.Bj;f8.prototype.getPlayerContextData=f8.prototype.XE;f8.prototype.setPlayerContextData=f8.prototype.kO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.Cx;f8.prototype.getReconnectTimeout=f8.prototype.Fl;f8.prototype.getAutoplayMode=f8.prototype.ME;f8.prototype.getAutoplayVideoId=f8.prototype.NE;f8.prototype.reconnect=f8.prototype.bP;
f8.prototype.sendMessage=f8.prototype.fO;g.r(m8,m7);g.h=m8.prototype;g.h.fe=function(a){return this.zd.$_gs(a)};
g.h.contains=function(a){return!!this.zd.$_c(a)};
g.h.get=function(a){return this.zd.$_g(a)};
g.h.start=function(){this.zd.$_st()};
g.h.add=function(a,b,c){this.zd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.zd.$_r(a,b,c)};
g.h.rq=function(a,b,c,d){this.zd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.u.length;a<b;++a)this.zd.$_ubk(this.u[a]);this.u.length=0;this.zd=null;m7.prototype.X.call(this)};
g.h.fP=function(){this.S("screenChange")};
g.h.PL=function(){this.S("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.gP;v7.prototype.$_gsppc=v7.prototype.UC;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.rq;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.fe;v7.prototype.$_gos=v7.prototype.TC;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.Ih;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.Q);G8.prototype.A=function(a){Lya(this,a.state)};g.r(H8,g.z);g.h=H8.prototype;g.h.X=function(){g.z.prototype.X.call(this);this.o.stop();this.u.stop();this.F.stop();this.P();var a=this.Qa;a.unsubscribe("proxyStateChange",this.TA,this);a.unsubscribe("remotePlayerChange",this.xm,this);a.unsubscribe("remoteQueueChange",this.Gp,this);a.unsubscribe("previousNextChange",this.PA,this);a.unsubscribe("nowAutoplaying",this.LA,this);a.unsubscribe("autoplayDismissed",this.kA,this);this.Qa=this.module=null};
g.h.fz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Qa.o)if(J8(this)){if(!$7(this.Qa).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":$7(this.Qa).eb()?this.Qa.pause():this.Qa.play();break;case "control_play":this.Qa.play();break;case "control_pause":this.Qa.pause();break;case "control_seek":this.C.Lx(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.h.lK=function(a){this.F.eF(a)};
g.h.HO=function(a){this.fz("control_subtitles_set_track",g.Mb(a)?null:a)};
g.h.hC=function(){var a=this.J.getOption("captions","track");g.Mb(a)||K8(this,a)};
g.h.Pb=function(a){this.module.Pb(a,this.J.getVideoData().lengthSeconds)};
g.h.zA=function(a){if(J8(this)){this.Qa.unsubscribe("remotePlayerChange",this.xm,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.Qa);if(b!==c.volume||a!==c.muted)this.Qa.setVolume(b,a),this.G.start();this.Qa.subscribe("remotePlayerChange",this.xm,this)}};
g.h.mL=function(){g.Mb(this.w)||Nya(this,this.w);this.A=!1};
g.h.TA=function(a,b){this.u.stop();2===b&&this.gC()};
g.h.xm=function(){if(J8(this)){this.o.stop();var a=$7(this.Qa);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.Sc=1;break;case 1082:case 1083:this.module.Sc=0;break;default:this.module.Sc=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.wC(8));this.fC();break;case 1085:case 3:I8(this,new g.wC(9));break;case 1083:case 0:I8(this,new g.wC(2));this.C.stop();this.Pb(this.J.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.wC(4));break;case 2:I8(this,new g.wC(4));
this.Pb(V7(a));break;case -1:I8(this,new g.wC(64));break;case -1E3:I8(this,new g.wC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=$7(this.Qa).o;var b=this.w;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.w=a,Nya(this,a));a=$7(this.Qa);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.G.isActive()||this.GC()}else Mya(this)};
g.h.PA=function(){this.J.S("mdxpreviousnextchange")};
g.h.Gp=function(){J8(this)||Mya(this)};
g.h.LA=function(a){isNaN(a)||this.J.S("mdxnowautoplaying",a)};
g.h.kA=function(){this.J.S("mdxautoplaycanceled")};
g.h.setAudioTrack=function(a){J8(this)&&this.Qa.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.h.seekTo=function(a,b){-1===$7(this.Qa).playerState?L8(this,a):b&&this.Qa.seekTo(a)};
g.h.GC=function(){if(J8(this)){var a=$7(this.Qa);this.events.bb(this.I);a.muted?this.J.mute():this.J.unMute();this.J.setVolume(a.volume);this.I=this.events.L(this.J,"onVolumeChange",this.zA)}};
g.h.fC=function(){this.o.stop();if(!this.Qa.fa()){var a=$7(this.Qa);a.eb()&&I8(this,new g.wC(8));this.Pb(V7(a));this.o.start()}};
g.h.gC=function(){this.u.stop();this.o.stop();var a=this.Qa.A.getReconnectTimeout();2==this.Qa.o&&!isNaN(a)&&this.u.start()};g.r(M8,g.Q);M8.prototype.Rb=function(){this.u.show()};
M8.prototype.w=function(){g.iO("https://support.google.com/youtube/answer/7640706")};
M8.prototype.A=function(){d6("mdx-manual-pairing-popup-ok");this.u.hide()};g.r(N8,g.Q);N8.prototype.Rb=function(){this.u.show()};
N8.prototype.w=function(){d6("mdx-privacy-popup-cancel");this.u.hide()};
N8.prototype.A=function(){d6("mdx-privacy-popup-confirm");this.u.hide()};g.r(O8,g.ON);O8.prototype.C=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.Sh=g.vb(a,this.w,this),g.QN(this,(0,g.Dc)(a,this.w)),a=this.J.getOption("remote","currentReceiver"),this.Cb(this.w(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.w=function(a){return a.key};
O8.prototype.cf=function(a){return"cast-selector-receiver"===a?"Cast...":this.Sh[a].name};
O8.prototype.jd=function(a){g.ON.prototype.jd.call(this,a);this.J.setOption("remote","currentReceiver",this.Sh[a]);this.u.jb()};g.r(P8,g.AL);g.h=P8.prototype;
g.h.create=function(){Fya(g.Gy(this.player.N()));this.subscriptions.push(g.Po("yt-remote-before-disconnect",this.iK,this));this.subscriptions.push(g.Po("yt-remote-connection-change",this.tM,this));this.subscriptions.push(g.Po("yt-remote-receiver-availability-change",this.RA,this));this.subscriptions.push(g.Po("yt-remote-auto-connect",this.rM,this));this.subscriptions.push(g.Po("yt-remote-receiver-resumed",this.qM,this));this.subscriptions.push(g.Po("mdx-privacy-popup-confirm",this.KN,this));this.subscriptions.push(g.Po("mdx-privacy-popup-cancel",
this.JN,this));this.subscriptions.push(g.Po("mdx-manual-pairing-popup-ok",this.mG,this));this.RA()};
g.h.load=function(){this.player.cancelPlayback();g.AL.prototype.load.call(this);this.Zd=new H8(this,this.player,this.Qa);var a=(a=Kya())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!==a&&this.Pb(a);Oya(this,this.Ac,this.Ac);g.WS(this.player.app,6)};
g.h.unload=function(){this.player.S("mdxautoplaycanceled");this.ah=this.af;g.Ie(this.Zd,this.Qa);this.Qa=this.Zd=null;g.AL.prototype.unload.call(this);g.WS(this.player.app,5);Q8(this)};
g.h.X=function(){g.Qo(this.subscriptions);g.AL.prototype.X.call(this)};
g.h.Kf=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.Zd.fz.apply(this.Zd,[a].concat(g.la(c)))};
g.h.getAdState=function(){return this.Sc};
g.h.aF=function(){return this.loaded?this.Zd.suggestion:null};
g.h.zf=function(){return this.Qa?$7(this.Qa).zf:!1};
g.h.hasNext=function(){return this.Qa?$7(this.Qa).hasNext:!1};
g.h.Pb=function(a,b){this.uy=a||0;this.player.S("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.uy};
g.h.getProgressState=function(){var a=$7(this.Qa),b=this.player.getVideoData();return{allowSeeking:g.O(this.player.N().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Rc():!a.isAdPlaying()&&this.player.Rc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.w?a.A+T7(a):a.A,isAtLiveHead:1>=(a.w?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.w?a.u+T7(a):a.u,seekableStart:0<a.B?a.B+
T7(a):a.B}};
g.h.nextVideo=function(){this.Qa&&this.Qa.nextVideo()};
g.h.Kp=function(){this.Qa&&this.Qa.Kp()};
g.h.iK=function(a){1===a&&(this.gu=this.Qa?$7(this.Qa):null)};
g.h.tM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.ah;this.loaded&&this.unload();this.Qa=a;this.gu=null;b.key!==this.af.key&&(this.ah=b,this.load())}else g.He(this.Qa),this.Qa=null,this.loaded&&(this.unload(),(a=this.gu)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.RA=function(){this.Sh=[this.af].concat(Hya());var a=y8()||this.af;R8(this,a);this.player.ra("onMdxReceiversChange")};
g.h.rM=function(){var a=y8();R8(this,a)};
g.h.qM=function(){this.ah=y8()};
g.h.KN=function(){this.ym=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.JN=function(){this.ym=!1;Q8(this);R8(this,this.af);this.ah=this.af;E8=!1;F8=null;this.player.playVideo()};
g.h.mG=function(){this.No=!0;Q8(this);g.qs("yt-remote-manual-pairing-warning-shown",!0,2592E3);E8=!1;F8&&A8(F8,1);F8=null};
g.h.Pc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Sh;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?P7():R8(this,b)),this.loaded?this.ah:this.af;case "quickCast":return 2===this.Sh.length&&"cast-selector-receiver"===this.Sh[1].key?(b&&P7(),!0):!1}};
g.h.Ou=function(){this.Qa.Ou()};
g.h.Sf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.PL.remote=P8;})(_yt_player);
